name: "phunt: Continuous Integration"

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

env:
  DO_NOT_TRACK: 1
  HUSKY: 0

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache turbo lint setup
        uses: actions/cache@v4
        with:
          path: .turbo
          key: lint-${{ runner.os }}-${{ matrix.node-version }}-turbo-${{ github.sha }}
          restore-keys: |
            lint-${{ runner.os }}-${{ matrix.node-version }}-turbo-

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install monorepo dependencies
        run: yarn install

      - name: Lint monorepo
        run: yarn lint

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        architecture: [x64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache turbo build setup
        uses: actions/cache@v4
        with:
          path: .turbo
          key: build-${{ runner.os }}-${{ matrix.node-version }}-${{ matrix.architecture }}-turbo-${{ github.sha }}
          restore-keys: |
            build-${{ runner.os }}-${{ matrix.node-version }}-${{ matrix.architecture }}-turbo-

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install monorepo dependencies
        run: yarn install

      - name: Build monorepo
        env:
          BUILD_ID: ${{ github.run_id }}
        run: yarn build

      - name: Test monorepo
        run: yarn test
