name: "phunt: Release Workflow"

on:
  release:
    types: [published]

env:
  DO_NOT_TRACK: 1
  HUSKY: 0

permissions:
  contents: write
  id-token: write

jobs:
  build-release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        architecture: [x64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache turbo build setup
        uses: actions/cache@v4
        with:
          path: .turbo
          key: build-${{ runner.os }}-${{ matrix.node-version }}-${{ matrix.architecture }}-turbo-${{ github.sha }}
          restore-keys: |
            build-${{ runner.os }}-${{ matrix.node-version }}-${{ matrix.architecture }}-turbo-

      - name: Enable corepack
        run: corepack enable

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: "https://registry.npmjs.org"
          cache: "yarn"

      - name: Install monorepo dependencies
        run: yarn install --immutable

      - name: Build monorepo
        env:
          BUILD_ID: ${{ github.run_id }}
        run: yarn build

      - name: Test monorepo
        run: yarn test

      - name: Publish monorepo packages
        run: yarn workspaces foreach --topological --no-private publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
