name: "phunt: Release Workflow"

on:
  push:
    tags:
      - "v*"

env:
  DO_NOT_TRACK: 1
  HUSKY: 0

permissions:
  contents: write
  id-token: write

jobs:
  build-release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 20.x ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache turbo build setup
        uses: actions/cache@v4
        with:
          path: .turbo
          key: build-${{ runner.os }}-${{ matrix.node-version }}-${{ matrix.architecture }}-turbo-${{ github.sha }}
          restore-keys: |
            build-${{ runner.os }}-${{ matrix.node-version }}-${{ matrix.architecture }}-turbo-

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
          cache: "pnpm"

      - name: Install monorepo dependencies
        run: pnpm install

      - name: Build monorepo
        env:
          BUILD_ID: ${{ github.run_id }}
        run: pnpm build

      - name: Test monorepo
        run: pnpm test

      - name: Publish monorepo packages
        run: pnpm publish -r
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  create-release:
    runs-on: ubuntu-latest

    needs: build-release

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
